//
//  ChessNotifications.h
//  iChessTable
//
//  Created by Jin Jin on 11-8-19.
//  Copyright 2011年 __MyCompanyName__. All rights reserved.
//

#ifndef iChessTable_ChessNotifications_h
#define iChessTable_ChessNotifications_h

//sends by View Controller and receives by Game Controller
#define NOTIFICATION_PLAYER_PIECE_SELECT    @"NOTIFICATION_PLAYER_PIECE_SELECT"
#define NOTIFICATION_PLAYER_PIECE_DROP      @"NOTIFICATION_PLAYER_PIECE_DROP"
#define NOTIFICATION_PLAYER_PIECE_MOVE      @"NOTIFICATION_PLAYER_PIECE_MOVE"
#define NOTIFICATION_REPLAY_START           @"NOTIFICATION_REPLAY_START"
#define NOTIFICAITON_REPLAY_END             @"NOTIFICAITON_REPLAY_END"
#define NOTIFICATION_REPLAY_PAUSE_RESUME    @"NOTIFICATION_REPLAY_PAUSE_RESUME"    
#define NOTIFICATION_REPLAY_FORWARD         @"NOTIFICATION_REPLAY_FORWARD"
#define NOTIFICATION_REPLAY_REWARD          @"NOTIFICATION_REPLAY_REWARD"
//sends by Game Controller and receiveds by View Controller
#define NOTIFICATION_GAME_ISSELECTLEGAL     @"NOTIFICATION_GAME_ISSELECTLEGAL"
#define NOTIFICATION_GAME_ISDROPLEGAL       @"NOTIFICATION_GAME_ISDROPLEGAL"
#define NOTIFICATION_GAME_ISMOVELEGAL       @"NOTIFICATION_GAME_ISMOVELEGAL"
//received by View Controller
#define NOTIFICATION_TABLE_UPDATE_BEGIN     @"NOTIFICATION_TABLE_UPDATE_BEGIN"
#define NOTIFICATION_TABLE_UPDATE_STEP      @"NOTIFICATION_TABLE_UPDATE_STEP"
#define NOTIFICATION_TABLE_UPDATE_END       @"NOTIFICATION_TABLE_UPDATE_END"

#endif
